import logging
from typing import List
from redis.asyncio import Redis
from app.schemas.alert import Alert
from app.core.notifier import BaseNotifier
from app.detectors.base import BaseDetector
from app.detectors.push_time import PushTimeDetector
from app.detectors.hacker_team import HackerTeamDetector
from app.detectors.repo_deleted_fast import RepoDeletedFastDetector

logger = logging.getLogger(__name__)

class EventProcessor:
    def __init__(self, redis_client: Redis, notifier: BaseNotifier):
        self.redis = redis_client
        self.notifier = notifier
        # Initialize all detectors
        self.detectors: List[BaseDetector] = [
            PushTimeDetector(),
            HackerTeamDetector(),
            RepoDeletedFastDetector()
        ]

    async def process_event(self, org_id: str, event_type: str, payload: dict) -> None:
        """
        Runs all applicable detectors on the event and notifies on alerts.
        """
        logger.debug(f"Processing {event_type} event for org: {org_id}")
        for detector in self.detectors:
            if detector.supports(event_type, payload):
                logger.debug(f"Running detector: {detector.name}")
                try:
                    alert = await detector.detect(org_id, event_type, payload, self.redis)
                    if alert:
                        logger.info(f"🚨 ALERT GENERATED by {detector.name} for org: {org_id}")
                        self.notifier.notify(alert)
                    else:
                        logger.debug(f"No suspicious activity detected by {detector.name}")
                except Exception as e:
                    logger.error(f"Error in detector {detector.name}: {e}", exc_info=True)
            else:
                logger.debug(f"Skipping detector {detector.name} (unsupported event type)")
